apiVersion: tekton.dev/v1beta1
kind: PipelineRun 
metadata: 
  generateName: md-lint-pipeline-run-
spec:
  pipelineRef:
    name: md-lint-pipeline
  params:
    - name: source-repo
      value: https://github.com/upslopeio/lint-markdown-files
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi